### PR TITLE
Lab10

### PR DESCRIPTION
**Pull request by al1ych**

### CODE REVIEW

**Review by SMore-Napi — APPROVED** [review]
Everything is super clear and nice!
Very comprehensive and detailed explanation about `Library Charts` and `Umbrella chart` 👍

Please provide your PR lab10 to lab9 link in a description, so it would be easier to navigate.

**Review by MikhailMarch — COMMENTED** [review]
Look nice

**Comment by emileyray** [comment]
LGTM

**Comment by Dablup** [comment]
Good job

**Pull request closed without merging**
