### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by al1ych**

### CODE REVIEW

**Review by MikhailMarch — APPROVED** [review]
Everything is fine
But you can extend you JS CI and add more features into it

**Comment by Dablup** [comment]
Looks good!

Only one moment: you can add workflows not only for pushes, but also for pull requests

**Comment by emileyray** [comment]
Looks nice! You've got many good, interesting original tests

**Comment by SMore-Napi** [comment]
Great work! Everything works fine.

**Pull request closed without merging**
