### PR TITLE
Lab6

### PR DESCRIPTION
**Pull request by Dablup**
PR in my repo: https://github.com/Dablup/devops_labs/pull/4

### CODE REVIEW

**Review by SMore-Napi — APPROVED** [review]
Looks pretty clear and neat. Maybe include in PR's description or comments the link to the Lab6 -> Lab5 PR, so it would be easier to look for commit changes.

**Comment by al1ych** [comment]
Хорошая работа

**Comment by emileyray** [comment]
LGTM)

**Review by MikhailMarch — COMMENTED** [review]
Look good

**Pull request closed without merging**
