### PR TITLE
Lab1 - Pull Request - Timur Nugaev

### PR DESCRIPTION
**Pull request by al1ych**
add python server on flask
add nodejs server on express
add documentation
add readme
add explanations on best practices used & pros and cons of the respective frameworks

### CODE REVIEW

**Comment by SMore-Napi** [comment]
Add `/app_javascript/.idea` and `/app_python/.idea` folders into `.gitignore`

**Comment by al1ych** [comment]
> Add `/app_javascript/.idea` and `/app_python/.idea` folders into `.gitignore`

thank you!
fixed in the last commit

p. s. they were already in .gitignore but i had pushed before i added them to .gitignore

**Review by afonyaa — COMMENTED** [review]
Добавь node_modules в игнор)

**Comment by al1ych** [comment]
> Добавь node_modules в игнор)

да добавил же)
хейтер

**Review by Dablup — COMMENTED** [review]
Looks good!)

**Comment by emileyray** [comment]
Nice

**Review by MikhailMarch — COMMENTED** [review]
Looks fine

**Pull request closed without merging**
