### PR TITLE
Lab9

### PR DESCRIPTION
**Pull request by al1ych**

### CODE REVIEW

**Review by MikhailMarch — COMMENTED** [review]
LGTM

**Comment by SMore-Napi** [comment]
Very nice! Super comprehensive terminology description with sources provided. Next time do not forget to create PR timely.

**Review by SMore-Napi — APPROVED** [review]
Very nice! Super comprehensive terminology explanation with sources provided. Next time do not forget to create PR timely.

**Comment by al1ych** [comment]
> Very nice! Super comprehensive terminology description with sources provided. Next time do not forget to create PR timely.

Не забуду)

**Comment by emileyray** [comment]
LGTM

**Comment by Dablup** [comment]
Looks good)

**Pull request closed without merging**
