### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by al1ych**

### CODE REVIEW

**Comment by emileyray** [comment]
Looks nice

**Comment by SMore-Napi** [comment]
Very nice 👍

**Comment by Dablup** [comment]
Everything is ok, don’t see any problems)

**Review by MikhailMarch — COMMENTED** [review]
Everything looks fine, but you can add .dockerignore fine to control files copy to your container

**Comment by al1ych** [comment]
> Everything looks fine, but you can add .dockerignore fine to control files copy to your container

Good idea

**Pull request closed without merging**
