### PR TITLE
Lab #1. Alexander Kurmazov 

### PR DESCRIPTION
**Pull request by AKurmazov**
Author: Alexander Kurmazov — a.kurmazov@innopolis.university

### CODE REVIEW

**Comment by afonyaa** [comment]
Outstanding! Precise and relevant documentation, well structured code and folders

**Comment by Maxkoz777** [comment]
Well done!

**Comment by none-word** [comment]
Good job!

**Comment by Homa3030** [comment]
Clean and nice solution, the one point that would make this solution more elegant is to add requirements file to specify the required packages with their versions

**Comment by AKurmazov** [comment]
> the one point that would make this solution more elegant is to add requirements file to specify the required packages with their versions

You probably missed it, but in both projects there are locked dependencies (i.e., _poetry.lock_ for **app_python**, _Cargo.lock_ for **app_rust**). It is a more reliable way to fix versions comparing to the requirements file.

**Pull request closed without merging**
