### PR TITLE
Lab4. Daniil Livitin

### PR DESCRIPTION
**Pull request by Dablup**
PR in my repo: https://github.com/Dablup/devops_labs/pull/2

### CODE REVIEW

**Comment by al1ych** [comment]
Good job on providing additional information on terraform import.
Even though it was not required, it helps to have this info right there.
Everything else looks according to the requirements.

**Review by SMore-Napi — APPROVED** [review]
Looks great. It's nice that you changed the code structure according to the previous feedback.

**Comment by emileyray** [comment]
Looks good

**Review by MikhailMarch — COMMENTED** [review]
Looks nice

**Pull request closed without merging**
