### PR TITLE
Лаб 12

### PR DESCRIPTION
**Pull request by emileyray**

### CODE REVIEW

**Comment by al1ych** [comment]
Looks good 
got the bonus too

**Review by SMore-Napi — APPROVED** [review]
Everything is nice. The best configMap description about `total_virtualization` course.

Your PR from lab 12 to lab 11 has a bit strange name. Maybe you should rename it from "Лаб 11" to "Лаб 12" since you are already have PR with Lab 11.

**Comment by emileyray** [comment]
> Looks good got the bonus too

я не делал бонусных заданий 👀

**Comment by emileyray** [comment]
> Everything is nice. The best configMap description about `total_virtualization` course.
> 
> Your PR from lab 12 to lab 11 has a bit strange name. Maybe you should rename it from "Лаб 11" to "Лаб 12" since you are already have PR with Lab 11.

thanks for pointing out!!!!

**Comment by al1ych** [comment]
> > Looks good got the bonus too
> 
> я не делал бонусных заданий 👀

значит я перепутал ПРы сори

**Pull request closed without merging**
