### PR TITLE
Lab1 - Igor Mpore

### PR DESCRIPTION
**Pull request by impore**
Submission of Lab1

### CODE REVIEW

**Comment by TalgatBektleuov** [comment]
Very cool design which pleases the eyes. Just one moment. I could not find information why you choose Flask. Overall, nice=)

**Comment by impore** [comment]
> Very cool design which pleases the eyes. Just one moment. I could not find information why you choose Flask. Overall, nice=)

The details about the chosen framework are in `PYTHON.md` file.

**Comment by TalgatBektleuov** [comment]
Sorry, forgot)) Thanks!

**Comment by Amirka-Kh** [comment]
I liked the structure. Here is that I can suggest, name your commit in imperative mood (so in your example: 'Create simple flask app', 'Complete server and templates', 'Update documentation'). Also, I would give pull request more specific name, but here it is unnecessary.

**Pull request closed without merging**
