### PR TITLE
Lab 6. Roman Soldatov

### PR DESCRIPTION
**Pull request by SMore-Napi**
Lab6 -> Lab5: https://github.com/SMore-Napi/DevOps_Innopolis/pull/4

### CODE REVIEW

**Comment by al1ych** [comment]
Лайк за бонусные задания 
Good job 👍

**Comment by al1ych** [comment]
Интересная реализация healthcheck

**Comment by emileyray** [comment]
LGTM

**Review by MikhailMarch — COMMENTED** [review]
Nice, includes bonus tasks

**Comment by Dablup** [comment]
Looks nice, good job

**Pull request closed without merging**
