### PR TITLE
Lab 7. Roman Soldatov

### PR DESCRIPTION
**Pull request by SMore-Napi**
Lab 7 -> Lab 6: https://github.com/SMore-Napi/DevOps_Innopolis/pull/5

### CODE REVIEW

**Comment by al1ych** [comment]
lgtm 👍🏿👍🏿

**Comment by al1ych** [comment]
looks all good to me 👍🏿👍🏿

**Review by MikhailMarch — COMMENTED** [review]
Look fine

**Comment by emileyray** [comment]
LGTM

**Comment by Dablup** [comment]
Everything is fine

**Pull request closed without merging**
