### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by Dablup**
PR in my repo: https://github.com/Dablup/devops_labs/pull/1

### CODE REVIEW

**Comment by al1ych** [comment]
good python workflow

maybe add a bit structure to the project? it may not be necessary but if the app grows it may be useful to have clean architecture for the project in the beginning. probably not going to grow too much though as the course focuses more on CI/CD so you're good)

**Review by MikhailMarch — APPROVED** [review]
Good
You can use pytest client to make requests in your test, this will reduce amount of your imports and increase code readability

**Comment by emileyray** [comment]
LGTM

**Review by SMore-Napi — COMMENTED** [review]
Agree with Timur and Misha: for the future reference think on project structure.

**Pull request closed without merging**
