### PR TITLE
Lab3

### PR DESCRIPTION
**Pull request by MikhailMarch**

### CODE REVIEW

**Comment by al1ych** [comment]
good job on workflow configuration, might have to steal things here and there in my workflow)

you forgot to add CI.md (if you're adding it) and describe the best practices used

also, maybe a little bit more information while describing things in .md files

**Comment by MikhailMarch** [comment]
> good job on workflow configuration, might have to steal things here and there in my workflow)
> 
> you forgot to add CI.md (if you're adding it) and describe the best practices used
> 
> also, maybe a little bit more information while describing things in .md files

Good point!
Added

**Comment by Dablup** [comment]
Everything is ok! Agree with Timur, workflows configurations are really good)

**Comment by emileyray** [comment]
LGTM, cant add anything besides what's described above

**Review by SMore-Napi — COMMENTED** [review]
Everything is done pretty clear.

**Pull request closed without merging**
