### PR TITLE
Lab4

### PR DESCRIPTION
**Pull request by AlexDest-Dev**

### CODE REVIEW

**Comment by SmetaninGleb** [comment]
Man, your work is so goood! It's like a holiday! Lets celebrate and write some code!

**Comment by Kastrylia** [comment]
Jesus Christ! Truly a masterpiece!

**Comment by ParfenovIgor** [comment]
Good work

**Comment by romanza705** [comment]
I can not write a better comment than Ruslan

**Comment by Fressermenschen** [comment]
GJ

**Pull request closed without merging**
