### PR TITLE
Lab 11. Roman Soldatov

### PR DESCRIPTION
**Pull request by SMore-Napi**
Lab 11 -> Lab 10: https://github.com/SMore-Napi/DevOps_Innopolis/pull/9

### CODE REVIEW

**Comment by al1ych** [comment]
good job
you didnt forget to include secrets.yaml)

**Review by MikhailMarch — COMMENTED** [review]
LGTM

**Comment by emileyray** [comment]
LGTM

**Comment by Dablup** [comment]
Seems good to me :)

**Pull request closed without merging**
