### PR TITLE
Lab 5. Roman Soldatov

### PR DESCRIPTION
**Pull request by SMore-Napi**
Lab5 -> Lab4: https://github.com/SMore-Napi/DevOps_Innopolis/pull/3

### CODE REVIEW

**Comment by emileyray** [comment]
LGTM!

**Review by Dablup — APPROVED** [review]
Everything is good, big plus for descriptive .md files

**Comment by al1ych** [comment]
Не вижу проблем, все норм

**Review by MikhailMarch — COMMENTED** [review]
LGTM

**Pull request closed without merging**
